apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  name: demo-pod1
  labels:
     app: demo-pod1
spec:
  containers:
  - name: demo-pod1-c
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "400Mi"
        cpu: "0.3"      
      requests:
        memory: "300Mi"
        cpu: "0.2"
